DoAn/DoAn/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAn.Models
{
    public class GioHang : Controller
    {
        DTDDEntities dt = new DTDDEntities();
        public int iMaSP { get; set; }
        public string sTenSP { get; set; }
        public string sAnh { get; set; }
        public double dDonGia { get; set; }
        public int iSoLuong { get; set; }
        public double dThanhTien
        {
            get { return iSoLuong * dDonGia; }
        }

        public GioHang(int MaSP)
        {
            iMaSP = MaSP;
            SanPham sp = dt.SanPhams.Single(s => s.MaSP == iMaSP);
            sTenSP = sp.TenSP;
            sAnh = sp.Anh   ;
            dDonGia = double.Parse(sp.GiaBan.ToString());
            iSoLuong = 1;
        }
    }

}

DoAn/DoAn/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;

namespace DoAn.Controllers
{
    public class GioHangController : Controller
    {
        DTDDEntities dt = new DTDDEntities();
        public List<GioHang> LayGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        public ActionResult ThemGioHang(int ms, string strURL)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang SanPham1 = lstGioHang.Find(sp => sp.iMaSP == ms);
            if (SanPham1 == null)
            {
                SanPham1 = new GioHang(ms);
                lstGioHang.Add(SanPham1);
                return Redirect(strURL);
            }
            else
            {
                SanPham1.iSoLuong++;
                return Redirect(strURL);
            }
        }
        private int TongSoLuong()
        {
            int tsl = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                tsl = lstGioHang.Sum(sp => sp.iSoLuong);
            }
            return tsl;
        }

        private double TongThanhTien()
        {
            double ttt = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                ttt += lstGioHang.Sum(sp => sp.dThanhTien);
            }
            return ttt;
        }
        public ActionResult GioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongThanhTien = TongThanhTien();

            return View(lstGioHang);
        }

        public ActionResult XoaGioHang(int MaSP)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.Single(s => s.iMaSP == MaSP);
            if (sp != null)
            {
                lstGioHang.RemoveAll(s => s.iMaSP == MaSP);
                return RedirectToAction("GioHang", "GioHang");
            }
            if (lstGioHang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang", "GioHang");
        }
        public ActionResult XoaGioHang_All()
        {
            List<GioHang> lstGioHang = LayGioHang();
            
            lstGioHang.Clear();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult CapNhatGioHang(int MaSP, FormCollection f)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.Single(s => s.iMaSP == MaSP);
            if (sp != null)
            {
                sp.iSoLuong = int.Parse(f["txtSoLuong"].ToString());
            }
            return RedirectToAction("GioHang", "GioHang");
        }
    }
}

DoAn/DoAn/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;

namespace DoAn.Controllers
{
    public class SanPhamController : Controller
    {
        DTDDEntities dt = new DTDDEntities();
        public ActionResult SanPhamPartial()
        {
            var ListSanPham = dt.SanPhams.OrderBy(s => s.TenSP).ToList();
            return View(ListSanPham);
        }
        public ActionResult XemChiTiet(int ms)
        {
            var ChiTiet = dt.SanPhams.Single(t => t.MaSP == ms);
            if (ChiTiet == null)
                return HttpNotFound();
            return View(ChiTiet);
        }

    }
}

DoAn/DoAn/Views/GioHang/GioHang.cshtml
@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/UserLayoutTest.cshtml";
}
@using DoAn.Models;
@model List<GioHang>

<h2>GIỎ HÀNG CỦA BẠN</h2>
<div class="card border-dark">
    <table class="table">
        <tr style="background-color: lightyellow">
            <th>MÃ SẢN PHẨM</th>
            <th>TÊN SẢN PHẨM</th>
            <th>ẢNH</th>
            <th>SỐ LƯỢNG</th>
            <th>ĐƠN GIÁ</th>
            <th>THÀNH TIẾN</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td width="12%">@item.iMaSP</td>
                <td width="26%">@item.iMaSP</td>
                <td width="22%"><img src="~/Images/@item.sAnh" width="50%"></td>
                @using (Html.BeginForm("CapNhatGioHang", "GioHang", new { @MaSP = item.iMaSP }))
                {
                    <td width="12%"> <input type="number" min="1" name="txtSoLuong" value="@item.iSoLuong" size="2"></td>
                    <td width="12%">@String.Format("{0:0,0}", item.dDonGia)</td>
                    <td width="16%">@String.Format("{0:0,0}", item.dThanhTien)</td>
                    <td><a href="@Url.Action("XemChiTiet", "SanPham", new { @ms = item.iMaSP})"> Details</a></td>
                    <td>@Html.ActionLink("Delete", "XoaGioHang", new { masp = item.iMaSP })</td>
                    <td><input type="submit" value="Update" class="btn btn-primary"></td>
                }
            </tr>
        }
        <tr style="background-color: lightyellow">
            <td colspan="3" style="color:blue; font-weight:bold; text-align:right;">Tổng cộng: </td>
            <td style="color:red; font-weightbold;">@ViewBag.TongSoLuong</td>
            <td></td>
            <td style="color: red; font-weightbold;">@String.Format("{0:0,0}", ViewBag.TongThanhTien) VNĐ</td>

        </tr>
    </table>
</div>