DoAn/DoAn/Controllers/LoaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;

namespace DoAn.Controllers
{
    public class LoaiController : Controller
    {
        DTDDEntities dt = new DTDDEntities();
        public ActionResult LoaiPartial()
        {
            return View(dt.Loais.Take(5).ToList());
        }

        public ActionResult DienThoaiPartial()
        {
            var tk = dt.Loais.Where(t => t.Note == "DT").ToList();
            return View(tk);
        }

        public ActionResult LapTopPartial( )
        {
            var tk = dt.Loais.Where(t => t.Note == "Lap").ToList();
            return View(tk);
        }

        public ActionResult PhuKienPartial()
        {
            var tk = dt.Loais.Where(t => t.Note == "PK").ToList();
            return View(tk);
        }

        public ActionResult SPTheoLoai(int maLoai)
        {
            var tk = dt.SanPhams.Where(s => s.MaLoai == maLoai).ToList();
            if (tk.Count == 0)
            {
                ViewBag.TB = "Không có sản phẩm thuộc loại này";
            }
            return View(tk);
        }
    }
}

DoAn/DoAn/Views/Shared/UserLayoutTest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
        <!--Bootstrap 4-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="text-center">     
        <div class="row" style="background-color:white; height:100px;">
            <div class="col-4 mt-2">
                <a href="#"><img src="~/Images/LogoMona.png" width="70%" class="rounded" /></a>
            </div>
            <div class="col-4 mt-4">
             <input class="form-control mx-auto" type="search" placeholder="Bạn tìm gì..." aria-label="Search" name="txt_Search">
        </div>
            <div class="col-1 mt-3">
                <button class="btn btn-link" type="submit">
                    <img src="~/Images/iconSeach.jpg" width="60px" height="40px" class="rounded" />
                </button>

                </div>
            </div>
        <div class="col-1 mt-3">
            
        </div>
        </div>
        
         <div class="row" style="background-color:white; text-align:center; height:60px;">
             <div class="col-12 mt-3 mx-auto">
                            <ul>
                                <li style="float:left; position:relative; display:block; width:150px; color:black; ">
                                    <a href="~/SanPham/SanPhamPartial" style="color: black;">TRANG CHỦ</a>
                                </li>
                                <li style="float: left; position: relative; display: block; width: 150px; color:black; " >
                                    <a href="#" style="color: black;">ĐĂNG KÝ</a>
                                </li>
                                <li style="float: left; position: relative; display: block; width: 150px; color:black; " >
                                   <a href="#" style="color: black;">ĐĂNG NHẬP</a>
                                </li>
                                <li style="float: left; position: relative; display: block; width: 150px; color:black;">
                                    <a href="#" style="color: black;">LIÊN HỆ</a>
                                </li>
                                <li style="float: left; position: relative; display: block; width: 150px; color:black;">
                                    <a href="~/GioHang/GioHang" style="color: black;"><img src="~/Images/iconGioHang.png" width="40px" height="30px" class="rounded" />(@ViewBag.TongSoLuong)</a>
                                </li>
                            </ul>
              </div>             
          </div>
        <!-- </div> -->
        <!--CONTAIN-->
        <div class="row">
            <div class="col col-md-2  card">
                @Html.Action("DienThoaiPartial", "Loai")
                @Html.Action("LapTopPartial", "Loai")
                @Html.Action("PhuKienPartial", "Loai")

            </div>
            <div class="col col-md-8"  style="background-color:white; ">
                <div class="row">
                    <div class ="col">

                        <div id="carouselExampleControls" class="carousel w-100 mx-auto mt-1" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="~/Images/banner1.jpg" class="d-block w-100 " alt="Ảnh 1" width="300px" height="400px" />
                            </div>
                            <div class="carousel-item">
                                <img src="~/Images/banner2.jpg" class="d-block w-100" alt="Ảnh 2" width="300px" height="400px"/>
                            </div>
                            <div class="carousel-item">
                                <img src="~/Images/banner3.jpg" class="d-block w-100 " alt="Ảnh 3"  width="300px" height="400px"/>
                            </div>
                             <div class="carousel-item">
                                <img src="~/Images/banner4.jpg" class="d-block w-100 " alt="Ảnh 4"  width="300px" height="400px"/>
                            </div>
                             <div style="float:left">
                                 <img src="~/Images/banner7.jpg" class="d-block w-100 " alt="Ảnh 5" width="300px" height="250px" />
                             </div>
                                 <div style="float:right"><img src="~/Images/banner5.jpg" class="d-block w-100 " alt="Ảnh 5" width="300px" height="250px" /></div>
                             </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    </div>
                </div>
                <div>
                        @RenderBody() 
                       



                </div>
            </div>
            <div class="col col-md-2 card">
               
                <ul class="list-group list-group-flush text-left">
                    <img src="/Images/banner6.jpg" class="d-block w-100 " alt="Ảnh 1" width="300px" height="400px" />
                   
                </ul>


            </div>
       </div>
        <!--Footer-->
        <div class="row" style="background-color: white; text-align: center;">
            <div class="col text-black mt-3 mb-3" style="text-align:center;">© CÔNG TY TNHH MONA MEDIA - MST : 0313728397 DO SỞ KHĐT TPHCM CẤP NGÀY 00/00/2019 /<br />ĐỊA CHỈ : 319 C16 Lý Thường Kiệt, phường 15, quận 11, TP Hồ Chí Minh<br />HOTLINE : 1900 636 648 - EMAIL : mon@mona.media </div>
        </div>
         </div>
    
</body>
</html>